version: '3.8'

services:
  django:
    image: ${APP_SERVICE_IMAGE}
    build: .
    container_name: django
    env_file:
      - .env
    ports:
      - "80:8000"
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - appnet

  postgres:
    image: ${DB_SERVICE_IMAGE}
    container_name: postgres
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 3s
    restart: always
    networks:
      - appnet
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:${PGADMIN_SERVICE_IMAGE_VERSION}
    container_name: pgadmin
    ports:
      - "5050:80"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
    restart: always
    networks:
      - appnet
    volumes:
      - pgadmindata:/var/lib/pgadmin

networks:
  appnet:

volumes:
  pgdata:
  pgadmindata: